export interface UnitSection {
  name: string;
  fields: Array<{ key: string; value: string }>;
}

export interface SystemdUnit {
  unitType: 'service' | 'timer' | 'socket' | 'mount' | 'automount' | 'path' | 'target';
  unitName: string;
  sections: UnitSection[];
}

export type SystemdUnitType = SystemdUnit['unitType'];

export const UNIT_TYPE_DESCRIPTIONS: Record<SystemdUnitType, string> = {
  service: 'Background service daemon',
  timer: 'Timer-based activation',
  socket: 'Socket-based activation',
  mount: 'Filesystem mount point',
  automount: 'Automated mount point',
  path: 'Path-based activation',
  target: 'Grouping of units',
};

export const DEFAULT_SECTIONS: Record<SystemdUnitType, string[]> = {
  service: ['Unit', 'Service', 'Install'],
  timer: ['Unit', 'Timer', 'Install'],
  socket: ['Unit', 'Socket', 'Install'],
  mount: ['Unit', 'Mount', 'Install'],
  automount: ['Unit', 'Automount', 'Install'],
  path: ['Unit', 'Path', 'Install'],
  target: ['Unit', 'Target'],
};

export const SECTION_FIELD_SUGGESTIONS: Record<string, string[]> = {
  Unit: [
    'Description',
    'Documentation',
    'Wants',
    'Requires',
    'Requisite',
    'BindsTo',
    'PartOf',
    'Upholds',
    'Before',
    'After',
    'OnFailure',
    'OnSuccess',
    'PropagatesReloadTo',
    'ReloadPropagatedFrom',
    'ReloadSignal',
    'Conflicts',
    'ConditionPathExists',
    'ConditionPathExistsGlob',
    'ConditionPathIsDirectory',
    'ConditionPathIsSymbolicLink',
    'ConditionPathIsMountPoint',
    'ConditionPathIsReadWrite',
    'ConditionDirectoryNotEmpty',
    'ConditionFileNotEmpty',
    'ConditionFileIsExecutable',
    'ConditionACPower',
    'ConditionHost',
    'ConditionKernelCommandLine',
    'ConditionMemory',
    'ConditionCPUs',
    'ConditionArchitecture',
    'ConditionVirtualization',
    'ConditionSecurity',
    'ConditionCapability',
    'ConditionEnvironment',
    'ConditionUser',
    'ConditionGroup',
    'ConditionControlGroupController',
    'AssertPathExists',
    'AssertPathIsDirectory',
    'AssertPathIsSymbolicLink',
    'AssertPathIsMountPoint',
    'AssertPathIsReadWrite',
    'AssertDirectoryNotEmpty',
    'AssertFileNotEmpty',
    'AssertFileIsExecutable',
    'AssertACPower',
    'AssertHost',
    'AssertArchitecture',
    'AssertVirtualization',
    'AssertSecurity',
    'AssertCapability',
    'AssertUser',
    'AssertGroup',
    'AssertControlGroupController',
    'SourcePath',
    'DefaultDependencies',
    'IgnoreOnIsolate',
    'IgnoreOnSnaphsot',
    'CollectMode',
    'FailureAction',
    'SuccessAction',
    'FailureActionExitStatus',
    'SuccessActionExitStatus',
    'JobTimeoutSec',
    'JobRunningTimeoutSec',
    'JobTimeoutAction',
    'JobTimeoutRebootArgument',
    'StartLimitIntervalSec',
    'StartLimitBurst',
    'StartLimitAction',
    'RebootArgument',
    'ConditionFirstBoot',
    'ConditionFirmware',
    'AssertFirmware',
    'ConditionNeedsUpdate',
    'AssertNeedsUpdate',
    'StopWhenUnneeded',
    'RefuseManualStart',
    'RefuseManualStop',
    'AllowIsolate',
  ],
  Service: [
    'Type',
    'ExecStart',
    'ExecStartPre',
    'ExecStartPost',
    'ExecCondition',
    'ExecStop',
    'ExecStopPost',
    'ExecReload',
    'Restart',
    'RestartSec',
    'RestartSteps',
    'RestartMaxDelaySec',
    'TimeoutStartSec',
    'TimeoutStopSec',
    'TimeoutAbortSec',
    'TimeoutCleanSec',
    'RuntimeMaxSec',
    'SuccessExitStatus',
    'RestartPreventExitStatus',
    'RestartForceExitStatus',
    'User',
    'Group',
    'DynamicUser',
    'SupplementaryGroups',
    'WorkingDirectory',
    'RootDirectory',
    'RootImage',
    'Environment',
    'EnvironmentFile',
    'PassEnvironment',
    'UnsetEnvironment',
    'StandardInput',
    'StandardOutput',
    'StandardError',
    'StandardInputData',
    'TTYPath',
    'TTYReset',
    'TTYVHangup',
    'TTYVTDisallocate',
    'SyslogIdentifier',
    'SyslogFacility',
    'SyslogLevel',
    'LogNamespace',
    'LogLevelMax',
    'LogExtraFields',
    'LimitNOFILE',
    'LimitNPROC',
    'LimitAS',
    'LimitRSS',
    'LimitCORE',
    'LimitMEMLOCK',
    'LimitFSIZE',
    'LimitSTACK',
    'LimitCPU',
    'LimitSIGPENDING',
    'LimitMSGQUEUE',
    'LimitNICE',
    'LimitRTPRIO',
    'LimitRTTIME',
    'Nice',
    'IOSchedulingClass',
    'IOSchedulingPriority',
    'CPUSchedulingPolicy',
    'CPUSchedulingPriority',
    'CPUSchedulingResetOnFork',
    'CPUAffinity',
    'CPUAccounting',
    'CPUWeight',
    'CPUQuota',
    'CPUQuotaPeriodSec',
    'MemoryMax',
    'MemoryHigh',
    'MemoryLow',
    'MemoryMin',
    'MemorySwapMax',
    'MemoryZSwapMax',
    'MemoryAccounting',
    'TasksMax',
    'TasksAccounting',
    'IOAccounting',
    'IOWeight',
    'IOReadWeight',
    'IOWriteWeight',
    'IODeviceWeight',
    'IOReadBandwidthMax',
    'IOWriteBandwidthMax',
    'IODeviceLatencyTargetSec',
    'NetworkNamespacePath',
    'PrivateNetwork',
    'NetworkLinkDown',
    'OOMScoreAdjust',
    'OOMPolicy',
    'UMask',
    'UtmpIdentifier',
    'KeyringMode',
    'ProtectSystem',
    'ProtectHome',
    'ProtectKernelTunables',
    'ProtectKernelModules',
    'ProtectKernelLogs',
    'ProtectControlGroups',
    'ProtectProc',
    'ProcSubset',
    'PrivateTmp',
    'PrivateDevices',
    'PrivateMounts',
    'PrivateUsers',
    'PrivateIPC',
    'ProtectClock',
    'ProtectHostname',
    'MemoryDenyWriteExecute',
    'RestrictRealtime',
    'RestrictSUIDSGID',
    'RestrictNamespaces',
    'RestrictAddressFamilies',
    'LockPersonality',
    'CapabilityBoundingSet',
    'AmbientCapabilities',
    'NoNewPrivileges',
    'DeviceAllow',
    'DevicePolicy',
    'SystemCallArchitectures',
    'SystemCallFilter',
    'SystemCallErrorNumber',
    'SystemCallLog',
    'RemoveIPC',
    'Delegate',
    'StateDirectory',
    'StateDirectoryMode',
    'CacheDirectory',
    'CacheDirectoryMode',
    'LogsDirectory',
    'LogsDirectoryMode',
    'ConfigurationDirectory',
    'ConfigurationDirectoryMode',
    'RuntimeDirectory',
    'RuntimeDirectoryMode',
    'RuntimeDirectoryPreserve',
    'BindPaths',
    'BindReadOnlyPaths',
    'MountImages',
    'TemporaryFileSystem',
    'ReloadSignal',
    'Sockets',
    'BusName',
    'NotifyAccess',
    'SdNotifySocket',
    'WatchdogSec',
    'FileDescriptorStoreMax',
    'ServiceTasksMax',
  ],
  Install: ['WantedBy', 'RequiredBy', 'Also', 'Alias', 'DefaultInstance'],
  Timer: [
    'OnCalendar',
    'OnActiveSec',
    'OnBootSec',
    'OnStartupSec',
    'OnUnitActiveSec',
    'OnUnitInactiveSec',
    'AccuracySec',
    'RandomizedDelaySec',
    'FixedRandomDelay',
    'Persistent',
    'WakeSystem',
    'RemainAfterElapse',
    'Unit',
    'OnClockChange',
    'OnTimezoneChange',
  ],
  Socket: [
    'ListenStream',
    'ListenDatagram',
    'ListenSequentialPacket',
    'ListenFIFO',
    'ListenNetlink',
    'ListenMessageQueue',
    'ListenSpecial',
    'Service',
    'Accept',
    'MaxConnections',
    'MaxConnectionsPerSource',
    'KeepAlive',
    'KeepAliveTime',
    'KeepAliveInterval',
    'KeepAliveProbes',
    'SocketUser',
    'SocketGroup',
    'SocketMode',
    'BindIPv6Only',
    'ReusePort',
    'SmackLabel',
    'SELinuxContextFromNet',
    'IPTOS',
    'IPTTL',
    'TriggerLimitBurst',
    'TriggerLimitIntervalSec',
  ],
  Mount: [
    'What',
    'Where',
    'Type',
    'Options',
    'TimeoutSec',
    'Sloppy',
    'LazyUnmount',
    'ForceUnmount',
    'NoSuid',
    'NoDev',
    'NoExec',
    'ReadWriteOnly',
    'RebootArgument',
  ],
  Automount: ['Where', 'DirectoryMode', 'TimeoutSec', 'ExtraOptions'],
  Path: [
    'PathExists',
    'PathExistsGlob',
    'PathChanged',
    'PathModified',
    'DirectoryNotEmpty',
    'Unit',
    'MakeDirectory',
    'DirectoryMode',
    'TriggerLimitBurst',
    'TriggerLimitIntervalSec',
  ],
  Target: [
    'Description',
    'Documentation',
    'Wants',
    'Requires',
    'BindsTo',
    'PartOf',
    'Conflicts',
    'Before',
    'After',
    'AllowIsolate',
    'StopWhenUnneeded',
    'RefuseManualStart',
    'RefuseManualStop',
  ],
};

export const TYPE_OPTIONS = [
  { value: 'simple', label: 'simple (default)' },
  { value: 'forking', label: 'forking' },
  { value: 'oneshot', label: 'oneshot' },
  { value: 'dbus', label: 'dbus' },
  { value: 'notify', label: 'notify' },
  { value: 'exec', label: 'exec' },
];

export const RESTART_OPTIONS = [
  { value: 'no', label: 'no (default)' },
  { value: 'on-success', label: 'on-success' },
  { value: 'on-failure', label: 'on-failure' },
  { value: 'on-abnormal', label: 'on-abnormal' },
  { value: 'on-watchdog', label: 'on-watchdog' },
  { value: 'on-abort', label: 'on-abort' },
  { value: 'always', label: 'always' },
];

export function generateUnitFile(unit: SystemdUnit): string {
  const lines: string[] = [];

  for (const section of unit.sections) {
    if (section.fields.length === 0) continue;
    lines.push(`[${section.name}]`);
    for (const field of section.fields) {
      if (field.key && field.value) {
        lines.push(`${field.key}=${field.value}`);
      }
    }
    lines.push('');
  }

  return lines.join('\n').trim();
}

export function getFilename(unit: SystemdUnit): string {
  const typeSuffix: Record<string, string> = {
    service: '.service',
    timer: '.timer',
    socket: '.socket',
    mount: '.mount',
    automount: '.automount',
    path: '.path',
    target: '.target',
  };
  return `${unit.unitName || 'unnamed'}${typeSuffix[unit.unitType] || '.service'}`;
}
